name: Lint pyzeebe

on: [push, pull_request]

jobs:
  type-checking:

    runs-on: ubuntu-latest

    container: python:3.8
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          pip install pipenv
          pipenv install --dev
      - name: Lint with mypy
        run: |
          pipenv run mypy pyzeebe

  import-checking:
    runs-on: ubuntu-latest

    container: python:3.8
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          pip install pipenv
          pipenv install --dev
      - name: Check imports
        run: |
          pipenv run isort . --check --diff
