name: Integration test pyzeebe

on:
  push:
    branches: [ master, development, feature/*, bugfix/*, maintenance/* ]
  pull_request:
    branches: [ master, development, feature/*, bugfix/*, maintenance/* ]

jobs:
  test:
    env:
      ZEEBE_ADDRESS: "zeebe:26500"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        zeebe-version: [ "0.23.7", "0.24.6", "0.25.3" ]

    container: python:3.5

    services:
      zeebe:
        image: camunda/zeebe:${{ matrix.zeebe-version }}
        ports:
          - 26500/tcp


    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          pip install pipenv
          pipenv install --dev

      - name: Sleep for 30 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: '30s'

      - name: Run integration tests
        run: |
          pipenv run pytest tests/integration
