# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test zeebepy

on:
  push:
    branches: [ master, development, feature/* ]
  pull_request:
    branches: [ master, development, feature/* ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install pipenv
        uses: dschep/install-pipenv-action@v1

      - name: Install dependencies
        run: |
          pip install pipenv
          pipenv install --dev
      - name: Test with pytest
        run: |
          pipenv run coverage run --source=. -m py.test
      - name: Coveralls Python
        uses: AndreMiras/coveralls-python-action@v20200413
