name: Test pyzeebe

on:
  push:
    branches: [ master, development, feature/*, bugfix/*, maintenance/*, enhancement/* ]
  pull_request:
    branches: [ master, development, feature/*, bugfix/*, maintenance/*, enhancement/* ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.5, 3.6, 3.7, 3.8]
    
    container: python:${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Test with pytest
        run: |
          coverage run --source=pyzeebe -m py.test tests/unit
      - name: Upload to coveralls
        run: |
          coveralls
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
