name: Integration test pyzeebe

on:
  push:
    branches: [ master, development, feature/*, bugfix/*, maintenance/* ]
  pull_request:
    branches: [ master, development, feature/*, bugfix/*, maintenance/* ]

jobs:
  test:
    env:
      ZEEBE_ADDRESS: "zeebe:26500"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        zeebe-version: [ "0.23.7", "0.24.5", "0.25.1" ]

    container: python:3.5

    services:
      zeebe:
        image: camunda/zeebe:${{ matrix.zeebe-version }}
        ports:
          - 26500/tcp
        options: >-
          --health-cmd "zbctl status --insecure "
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5


    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          pip install pipenv
          pipenv install --dev

      - name: Run integration tests
        run: |
          pipenv run pytest tests/integration
