name: Integration test pyzeebe

on:
  push:
    branches: [ master, development, feature/*, bugfix/*, maintenance/*, enhancement/* ]
  pull_request:
    branches: [ master, development, feature/*, bugfix/*, maintenance/*, enhancement/* ]

jobs:
  test:
    env:
      ZEEBE_ADDRESS: "zeebe:26500"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        zeebe-version: [ "0.23.6", "0.24.3" ]
        python-version: [ 3.5, 3.6, 3.7, 3.8 ]

    container: python:${{ matrix.python-version }}

    services:
      zeebe:
        image: camunda/zeebe:${{ matrix.zeebe-version }}
        ports:
          - 26500/tcp

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run integration tests
        run: |
          pytest tests/integration
