name: Test pyzeebe

on:
  push:
    branches: [ master, development, feature/*, bugfix/* ]
  pull_request:
    branches: [ master, development, feature/*, bugfix/* ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        zeebe-version: [ "0.20.0", "0.21.0", "0.22.0", "0.23.0", "0.24.0" ]
        python-version: [ 3.5, 3.6, 3.7, 3.8 ]

    services:
      zeebe:
        image: camunda/zeebe:${{ matrix.zeebe-version }}
        ports:
          - 26500/tcp

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          zeebe-version: ${{ matrix.zeebe-version }}
      - name: Install pipenv
        uses: dschep/install-pipenv-action@v1

      - name: Install dependencies
        run: |
          pip install pipenv
          pipenv install --dev
      - name: Wait / Sleep
        uses: jakejarvis/wait-action@v0.1.0
        with:
          time: 30s

      - name: Run integration tests
        run: |
          pipenv run pytest tests
